// packages/web-haptics/src/react/useWebHaptics.ts
"use client";

import { useRef, useEffect, useCallback } from "react";
import { WebHaptics } from "../lib/web-haptics";
import type {
  HapticInput,
  TriggerOptions,
  WebHapticsOptions,
} from "../lib/web-haptics/types";

export function useWebHaptics(options?: WebHapticsOptions) {
  const instanceRef = useRef<WebHaptics | null>(null);

  if (instanceRef.current === null) {
    instanceRef.current = new WebHaptics(options);
  }

  useEffect(() => {
    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, []);

  useEffect(() => {
    instanceRef.current?.setDebug(options?.debug ?? false);
  }, [options?.debug]);

  useEffect(() => {
    instanceRef.current?.setShowSwitch(options?.showSwitch ?? false);
  }, [options?.showSwitch]);

  const trigger = useCallback(
    (input?: HapticInput, options?: TriggerOptions) =>
      instanceRef.current?.trigger(input, options),
    [],
  );

  const cancel = useCallback(() => instanceRef.current?.cancel(), []);

  const isSupported = WebHaptics.isSupported;

  return { trigger, cancel, isSupported };
}

// packages/web-haptics/src/solid/useWebHaptics.ts
import { createEffect, on, onCleanup, onMount } from "solid-js";
import { WebHaptics } from "../lib/web-haptics";
import type {
  HapticInput,
  TriggerOptions,
  WebHapticsOptions,
} from "../lib/web-haptics/types";

export function useWebHaptics(options?: WebHapticsOptions) {
  let instance: WebHaptics | null = null;

  onMount(() => {
    instance = new WebHaptics(options);
  });

  onCleanup(() => {
    instance?.destroy();
    instance = null;
  });

  createEffect(
    on(
      () => options?.debug,
      (debug) => {
        instance?.setDebug(debug ?? false);
      },
      { defer: true },
    ),
  );

  createEffect(
    on(
      () => options?.showSwitch,
      (showSwitch) => {
        instance?.setShowSwitch(showSwitch ?? false);
      },
      { defer: true },
    ),
  );

  const trigger = (input?: HapticInput, options?: TriggerOptions) =>
    instance?.trigger(input, options);
  const cancel = () => instance?.cancel();
  const isSupported = WebHaptics.isSupported;

  return { trigger, cancel, isSupported };
}
