// apps/svelte-example/src/App.svelte
<script lang="ts">
  import { createWebHaptics } from "web-haptics/svelte";

  const { trigger } = createWebHaptics();
</script>

<div class="container">
  <button on:click={() => trigger()}>Tap me</button>
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    font-size: 2rem;
  }
</style>

// apps/solid-example/src/App.tsx
import { useWebHaptics } from "web-haptics/solid";

export default function App() {
  const { trigger } = useWebHaptics();

  return (
    <div
      style={{
        display: "flex",
        "justify-content": "center",
        "align-items": "center",
        height: "100vh",
        "font-size": "2rem",
      }}
    >
      <button onClick={() => trigger()}>Tap me</button>
    </div>
  );
}
